version: '3.8'

services:
  space-trader:
    build:
      context: .
      dockerfile: Containerfile
    container_name: space-trader
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - GALAXY_SIZE=${GALAXY_SIZE:-20}
      - TOTAL_NPCS=${TOTAL_NPCS:-100}
      - TICK_INTERVAL_MS=${TICK_INTERVAL_MS:-30000}
    volumes:
      - ./data:/app/.local-storage:Z
      - ./logs:/app/logs:Z
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3001/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
